In [4]:
import pandas as pd

df = pd.read_csv("final_balanced_dataset.csv")

df.head()

,Unnamed: 0,nli_label,reasoning,claim,evidence
0,2420,1,الدليل يشير إلى أن المقترح هو دراسة الجدوى وال...,المقترح هو دراسه الجدوي والاثار المترتبه علي ت...,"وقال المسحل لبرنامج ""في المرمي"": المقترح هو در..."
1,644,0,الدليل المقدم لا يوضح بشكل واضح ما إذا كان الأ...,الادعاء الرئيسي هو ان القوائم المشاركه في الان...,"يتمتع بشعبيه وقبول عند غالبيه التيارات""، وبدان..."
2,286,2,الادعاء يُشير إلى احتمالية أن يكون برنامج حمدو...,برنامج حمدوك الحكومي الجديد قد يخلق استقطابا و...,توافق وطني بين مكونات مجتمع غني بتنوعه الثقافي...
3,292,0,الادعاء يقول إن تحرير الأقصى تم بفضل المقاومة....,اصبحنا اقرب لتحرير الاقصي بفضل المقاومه.,الاقصي»، اجتماعات منفصله مع من «الاطار التنسيق...
4,1577,2,من الملاحظ أن الدليل يشير إلى أنه من ثوابت الت...,لن يشارك التيار الوطني الحر في حكومه سعد الحري...,الذي له خصوصيه سنيه، ومن ثوابتنا ان نكون داعمي...

In [6]:
df["ID"] = df["Unnamed: 0"]
df_fianl = df[["ID","nli_label", "claim", "evidence"]]

df_fianl.head()

,ID,nli_label,claim,evidence
0,2420,1,المقترح هو دراسه الجدوي والاثار المترتبه علي ت...,"وقال المسحل لبرنامج ""في المرمي"": المقترح هو در..."
1,644,0,الادعاء الرئيسي هو ان القوائم المشاركه في الان...,"يتمتع بشعبيه وقبول عند غالبيه التيارات""، وبدان..."
2,286,2,برنامج حمدوك الحكومي الجديد قد يخلق استقطابا و...,توافق وطني بين مكونات مجتمع غني بتنوعه الثقافي...
3,292,0,اصبحنا اقرب لتحرير الاقصي بفضل المقاومه.,الاقصي»، اجتماعات منفصله مع من «الاطار التنسيق...
4,1577,2,لن يشارك التيار الوطني الحر في حكومه سعد الحري...,الذي له خصوصيه سنيه، ومن ثوابتنا ان نكون داعمي...

In [7]:
df_fianl.to_csv("final_balanced_dataset.csv")